const servicesIT = [
  'AREE PICNIC',
  'FONTANELLE CON ACQUA POTABILE',
  'DOCCE',
  'AREA CAMPING',
  'BAGNI E SERVIZI IGENICI',
  'BUON CIBO',
  'BIRRA FRESCA',
];

const servicesEN = [
  'PICNIC AREAS',
  'DRINKING FOUNTAINS',
  'SHOWERS',
  'CAMPING AREA',
  'RESTROOMS AND TOILETS',
  'GOOD FOOD',
  'COLD BEER',
];

export { servicesIT, servicesEN };
